# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-16 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0021_auto_20161221_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='CHEMBLCompound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chembl_id', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CHEMBLTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chembl_id', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='compound',
            name='related_ChEMBL_compounds',
            field=models.ManyToManyField(blank=True, to='compounds.CHEMBLCompound'),
        ),
        migrations.AddField(
            model_name='compound',
            name='related_ChEMBL_targets',
            field=models.ManyToManyField(blank=True, to='compounds.CHEMBLTarget'),
        ),
    ]
